[package]
name = "dicor-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "dicor_rs"
path = "src/lib.rs"

[dependencies]
dicom-object = "0.10"
dicom-core = "0.10"
blake3 = "1.4"
chrono = { version = "0.4", features = ["serde"] }
num-bigint = "0.4"
hex = "0.4"
dicom-dictionary-std = "0.10"
charls = { version = "0.4.2", features = ["static"] }

[dev-dependencies]
tempfile = "3"