on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - run: pip install -r requirements.txt
    - run: nicegui-pack --name "Uploader" nice.py
    # Optionally verify that it works (provided that it does not need user interaction)
    - uses: actions/upload-artifact@v4
      with:
        name: release
        path: dist/*
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
